const constantsValues = {
  "0x13881": {
    chainID: "0x13881",
    forwarder: "0x69015912AA33720b842dCD6aC059Ed623F28d9f7",
    blockExplorer: "https://mumbai.polygonscan.com/address/",
    ChainName: "Mumbai polygon testnet",
    slug: "mumbai",
    openSeaCollection: "https://testnets.opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://testnets.opensea.io/assets/mumbai/",
    raribleCollection: "https://testnet.rarible.com/collection/polygon/",
  },

  "0x89": {
    chainID: "0x89",
    forwarder: "0xf0511f123164602042ab2bCF02111fA5D3Fe97CD",
    blockExplorer: "https://polygonscan.com/address/",
    ChainName: "Polygon mainnet",
    slug: "polygon",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://opensea.io/assets/matic/",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x51": {
    chainID: "0x51",
    blockExplorer: "https://blockscout.com/shibuya/address/",
    ChainName: "Astar Shibuya Testnet",
    slug: "shibuya",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x1": {
    chainID: "0x1",
    forwarder: "0xd43Ed82B8d822cB1a04ce84b5332e0B2DDf97760",
    blockExplorer: "https://etherscan.io/address/",
    ChainName: "Ethereum mainnet",
    slug: "ethereum",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://opensea.io/assets/ethereum/",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x5": {
    chainID: "0x5",
    blockExplorer: "https://goerli.etherscan.io/address/",
    ChainName: "Eth Goerli testnet",
    slug: "goerli",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://testnets.opensea.io/assets/goerli/",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x250": {
    chainID: "0x250",
    blockExplorer: "https://astar.network/address/",
    ChainName: "Astar Mainnet",
    slug: "astar",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x144": {
    chainID: "0x144",
    blockExplorer: "https://explorer.zksync.io/address/",
    ChainName: "zkSync Mainnet",
    slug: "zkSync",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x118": {
    chainID: "0x118",
    blockExplorer: "https://zksync2-testnet.zkscan.io/address/",
    ChainName: "zkSync Testnet",
    slug: "zkSynctestnet",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x1388": {
    chainID: "0x1388",
    blockExplorer: "https://explorer.testnet.mantle.xyz", //todo
    ChainName: "Mantle Mainnet",
    slug: "Mantle",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x1389": {
    chainID: "0x1389",
    blockExplorer: "https://explorer.testnet.mantle.xyz",
    ChainName: "Mantle Testnet",
    slug: "Mantletestnet",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0xA4B1": {
    chainID: "0xA4B1",
    blockExplorer: "https://explorer.arbitrum.io/address/",
    ChainName: "Arbitrum one mainnet",
    slug: "arbitrum",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://opensea.io/assets/arbitrum-nova/",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x66EED": {
    chainID: "0x66EED",
    blockExplorer: "https://goerli.arbiscan.io/address/",
    ChainName: "Arbitrum goerli testnet",
    slug: "arbitrumgoerli",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://opensea.io/assets/matic/", //todo
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x42": {
    chainID: "0x42",
    blockExplorer: "https://www.oklink.com/oktc/address/",
    ChainName: "OKC Mainnet",
    slug: "okc",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0xA86A": {
    chainID: "0xA86A",
    blockExplorer: "https://subnets.avax.network/address/",
    ChainName: "Avalanche mainnet",
    slug: "avalanche",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://opensea.io/assets/avalanche/",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0xA869": {
    chainID: "0xA869",
    blockExplorer: "https://subnets-test.avax.network/address/",
    ChainName: "Avalanche fuji testnet",
    slug: "fuji",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    openSeaNFTDetails: "https://opensea.io/assets/matic/", //todo
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
  "0x41": {
    chainID: "0x41",
    blockExplorer: "https://www.oklink.com/oktc-test/address/",
    ChainName: "OKC Testnet",
    slug: "okctestnet",
    openSeaCollection: "https://opensea.io/assets?search[query]=",
    raribleCollection: "https://rarible.com/collection/polygon/",
  },
};

export default constantsValues;
